@baseUrl = "https://httpbin.org"

# @name Send XML
POST {{baseUrl}}/anything
Accept: application/json
Content-Type: application/xml

<?xml version="1.0"?>
<message>
  <text>Hello from lazyrest</text>
</message>

# @name Send GraphQL
POST {{baseUrl}}/anything
Accept: application/json
X-REQUEST-TYPE: GraphQL

query Example($id: ID!) {
  viewer(id: $id) {
    id
    name
  }
}

{
  "id": "lazyrest-example-001"
}
